server {
    listen 80;
    server_name technologyradar.alwaysmoveforward.com;

    resolver 127.0.0.11 valid=10s;
    set $upstream http://techradarui:80;

    location / {
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name manage.technologyradar.alwaysmoveforward.com;

    resolver 127.0.0.11 valid=10s;
    set $upstream http://techradarui:80;

    location / {
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name admin.technologyradar.alwaysmoveforward.com;

    resolver 127.0.0.11 valid=10s;
    set $upstream http://techradarui:80;

    location / {
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
