server.port=8082

***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***

com.alwaysmoveforward.useEnvironmentForConfiguration=false
server.error.whitelabel.enabled=false

com.alwaysmoveforward.cookieSecret=dummy
spring.session.store-type=none
