export const SETCURRENTUSER = "SETCURRENTUSER";
export const ADDUSERS = "ADDUSERS";
export const ADDROLES = "ADDROLES";
export const SETMANAGEUSERSSELECTEDUSER = "SETMANAGEUSERSSELECTEDUSER";
export const SET_VIEWED_SUBSCRIPTION = "SET_VIEWED_SUBSCRIPTION";